# Generated by Django 5.1.2 on 2024-10-21 01:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('codcargo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codcli', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=255)),
                ('data_cas', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('coddep', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('coddesp', models.AutoField(primary_key=True, serialize=False)),
                ('desp', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='VProduto',
            fields=[
                ('codpro', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('codfor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('ende', models.CharField(max_length=255)),
                ('vpc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ve', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('codtmarc', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProduto',
            fields=[
                ('codtip', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('codf', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_nasc', models.DateField()),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=255)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('Contrato', 'Contrato'), ('Efetivo', 'Efetivo')], max_length=10)),
                ('data_entrada', models.DateField()),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('codcarg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbbase.cargo')),
                ('coddep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbbase.departamento')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('codatv', models.AutoField(primary_key=True, serialize=False)),
                ('tarefa', models.CharField(max_length=255)),
                ('dia', models.DateField()),
                ('codf_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to=settings.AUTH_USER_MODEL)),
                ('codf_gerente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gerente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('codpro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dbbase.vproduto')),
                ('quantidade', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Desconto',
            fields=[
                ('coddes', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('di', models.DateField()),
                ('dt', models.DateField()),
                ('codf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('codpro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbbase.vproduto')),
            ],
        ),
        migrations.CreateModel(
            name='Carregamento',
            fields=[
                ('codcar', models.AutoField(primary_key=True, serialize=False)),
                ('df', models.DateField()),
                ('dv', models.DateField()),
                ('lote', models.CharField(max_length=50)),
                ('codpro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbbase.vproduto')),
            ],
        ),
        migrations.AddField(
            model_name='vproduto',
            name='codmarc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbbase.marca'),
        ),
        migrations.CreateModel(
            name='Perda',
            fields=[
                ('codper', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.PositiveIntegerField()),
                ('dt', models.DateField()),
                ('codpro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbbase.vproduto')),
            ],
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('codponto', models.AutoField(primary_key=True, serialize=False)),
                ('diah', models.DateTimeField()),
                ('codf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='vproduto',
            name='codtip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbbase.tipoproduto'),
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('codvend', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=14, null=True)),
                ('data_hora', models.DateTimeField()),
                ('codcli', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbbase.cliente')),
                ('codf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PVenda',
            fields=[
                ('codpv', models.AutoField(primary_key=True, serialize=False)),
                ('codpro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbbase.vproduto')),
                ('codvend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbbase.venda')),
            ],
        ),
    ]
