# Generated by Django 5.1.2 on 2024-10-12 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbbase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('codtmarc', models.CharField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProduto',
            fields=[
                ('codtip', models.CharField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='codmarc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dbbase.marca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='codtip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dbbase.tipoproduto'),
            preserve_default=False,
        ),
    ]
