# Generated by Django 5.1.2 on 2024-10-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbbase', '0002_marca_tipoproduto_produto_codmarc_produto_codtip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='codtmarc',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipoproduto',
            name='codtip',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
