# Generated by Django 5.1.2 on 2024-10-12 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbbase', '0003_alter_marca_codtmarc_alter_tipoproduto_codtip'),
    ]

    operations = [
    ]
