# Generated by Django 5.1.2 on 2024-10-12 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbbase', '0004_auto_20241012_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='codmarc',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
    ]
