# Generated by Django 5.1.2 on 2024-10-12 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbbase', '0005_remove_produto_codmarc_delete_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='codtip',
        ),
        migrations.DeleteModel(
            name='TipoProduto',
        ),
    ]
