# Generated by Django 5.1.2 on 2024-10-12 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbbase', '0007_marca_tipoproduto_produto_codmarc_produto_codtip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='codmarc',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='codtip',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='valor',
        ),
    ]
