# Generated by Django 5.1.2 on 2024-10-12 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbbase', '0008_remove_produto_codmarc_remove_produto_codtip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='codf_funcionario',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='codf_gerente',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='codcarg',
        ),
        migrations.RemoveField(
            model_name='carregamento',
            name='codpro',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='coddep',
        ),
        migrations.RemoveField(
            model_name='desconto',
            name='codpro',
        ),
        migrations.DeleteModel(
            name='Despesa',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='codpro',
        ),
        migrations.DeleteModel(
            name='Fornecedor',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='codf',
        ),
        migrations.RemoveField(
            model_name='ponto',
            name='codf',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.RemoveField(
            model_name='perda',
            name='codpro',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='codpro',
        ),
        migrations.DeleteModel(
            name='TipoProduto',
        ),
        migrations.DeleteModel(
            name='Atividade',
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.DeleteModel(
            name='Carregamento',
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
        migrations.DeleteModel(
            name='Desconto',
        ),
        migrations.DeleteModel(
            name='Estoque',
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
        migrations.DeleteModel(
            name='Ponto',
        ),
        migrations.DeleteModel(
            name='Perda',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
