# Generated by Django 5.1.2 on 2024-10-12 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dbbase', '0009_remove_atividade_codf_funcionario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('codcargo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('coddep', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('coddesp', models.AutoField(primary_key=True, serialize=False)),
                ('desp', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('codpro', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('codfor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('ende', models.CharField(max_length=255)),
                ('vpc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ve', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('codtmarc', models.IntegerField(default=55, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProduto',
            fields=[
                ('codtip', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('codpro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dbbase.produto')),
                ('quantidade', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Desconto',
            fields=[
                ('coddes', models.AutoField(primary_key=True, serialize=False)),
                ('di', models.DateField()),
                ('dt', models.DateField()),
                ('codpro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbbase.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Carregamento',
            fields=[
                ('codcar', models.AutoField(primary_key=True, serialize=False)),
                ('df', models.DateField()),
                ('dv', models.DateField()),
                ('lote', models.CharField(max_length=50)),
                ('codpro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbbase.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('codf', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('data_nasc', models.DateField()),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('Contrato', 'Contrato'), ('Efetivo', 'Efetivo')], max_length=10)),
                ('data_entrada', models.DateField()),
                ('senha', models.CharField(max_length=128)),
                ('codcarg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbbase.cargo')),
                ('coddep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbbase.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('codatv', models.AutoField(primary_key=True, serialize=False)),
                ('tarefa', models.CharField(max_length=255)),
                ('dia', models.DateField()),
                ('codf_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to='dbbase.funcionario')),
                ('codf_gerente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gerente', to='dbbase.funcionario')),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='codmarc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbbase.marca'),
        ),
        migrations.CreateModel(
            name='Perda',
            fields=[
                ('codper', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.PositiveIntegerField()),
                ('dt', models.DateField()),
                ('codpro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbbase.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('codponto', models.AutoField(primary_key=True, serialize=False)),
                ('diah', models.DateTimeField()),
                ('codf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbbase.funcionario')),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='codtip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbbase.tipoproduto'),
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('codf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbbase.funcionario')),
                ('codpro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbbase.produto')),
            ],
        ),
    ]
