# Generated by Django 5.1.2 on 2024-10-12 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbbase', '0012_alter_atividade_codatv_alter_cargo_codcargo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produto',
            new_name='VProduto',
        ),
    ]
