# Generated by Django 5.1.2 on 2024-10-12 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbbase', '0014_alter_funcionario_options_alter_funcionario_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='senha',
        ),
    ]
