# Generated by Django 5.1.2 on 2024-10-12 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbbase', '0015_remove_funcionario_senha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={},
        ),
        migrations.AlterModelManagers(
            name='funcionario',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='password',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='username',
        ),
    ]
