# Generated by Django 5.1.2 on 2024-10-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbbase', '0017_alter_funcionario_options_alter_funcionario_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='data_nasc',
            field=models.DateField(null=True),
        ),
    ]
