# Generated by Django 5.1.2 on 2024-10-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbbase', '0019_alter_funcionario_cpf_alter_funcionario_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='data_entrada',
            field=models.DateField(null=True),
        ),
    ]
