# Generated by Django 5.1.2 on 2024-10-12 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbbase', '0020_alter_funcionario_data_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='codcarg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbbase.cargo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='coddep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbbase.departamento'),
        ),
    ]
