# Generated by Django 5.1.2 on 2024-10-12 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbbase', '0021_alter_funcionario_codcarg_alter_funcionario_coddep'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={},
        ),
        migrations.AlterModelTable(
            name='funcionario',
            table='Funcionario',
        ),
    ]
