# Generated by Django 5.1.2 on 2024-10-12 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbbase', '0022_alter_funcionario_options_alter_funcionario_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='funcionario',
            table=None,
        ),
    ]
