# Generated by Django 5.1.2 on 2024-10-12 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbbase', '0023_alter_funcionario_options_alter_funcionario_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name': 'Funcionario', 'verbose_name_plural': 'Funcionarios'},
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='nome',
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='codcarg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbbase.cargo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='coddep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbbase.departamento'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_entrada',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_nasc',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='endereco',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
