# Generated by Django 5.1.2 on 2024-10-14 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbbase', '0024_alter_funcionario_options_remove_funcionario_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='desconto',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
