# Generated by Django 5.1.2 on 2024-10-14 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbbase', '0026_desconto_codf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codcli', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=255)),
                ('data_cas', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='venda',
            name='codpro',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='id',
        ),
        migrations.AddField(
            model_name='venda',
            name='codvend',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='cpf',
            field=models.CharField(default=1, max_length=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='desconto',
            name='codf',
            field=models.ForeignKey(default=55, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='codcli',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbbase.cliente'),
        ),
        migrations.CreateModel(
            name='PVenda',
            fields=[
                ('codpv', models.AutoField(primary_key=True, serialize=False)),
                ('codpro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbbase.vproduto')),
                ('codvend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbbase.venda')),
            ],
        ),
    ]
