# Generated by Django 5.1.2 on 2024-10-14 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbbase', '0029_venda_pvenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='codcli',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='codf',
        ),
        migrations.DeleteModel(
            name='PVenda',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
