# Generated by Django 5.1.2 on 2024-10-14 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbbase', '0031_venda_pvenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='codcli',
        ),
        migrations.RemoveField(
            model_name='pvenda',
            name='codpro',
        ),
        migrations.RemoveField(
            model_name='pvenda',
            name='codvend',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='codf',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='PVenda',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
