# Generated by Django 5.1.2 on 2024-10-14 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbbase', '0032_remove_venda_codcli_remove_pvenda_codpro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codcli', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=255)),
                ('data_cas', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('codvend', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=14)),
                ('data_hora', models.DateTimeField()),
                ('codcli', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbbase.cliente')),
                ('codf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PVenda',
            fields=[
                ('codpv', models.AutoField(primary_key=True, serialize=False)),
                ('codpro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbbase.vproduto')),
                ('codvend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbbase.venda')),
            ],
        ),
    ]
