# Generated by Django 5.1.2 on 2024-10-19 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbbase', '0033_cliente_venda_pvenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desconto',
            name='codf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='venda',
            name='cpf',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.DeleteModel(
            name='Estoque',
        ),
    ]
