# Generated by Django 5.1.2 on 2024-10-19 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbbase', '0034_alter_desconto_codf_alter_venda_cpf_delete_estoque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('codpro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dbbase.vproduto')),
                ('quantidade', models.PositiveIntegerField()),
            ],
        ),
    ]
